[build]
  command = "npm run build"
  publish = ".next"

# ---- Allow assets to pass through ----
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/favicon*"
  to = "/favicon.svg"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# ---- Maintenance catch-all ----
[[redirects]]
  from = "/*"
  to = "/maintenance.html"
  status = 200
  force = true
