[build]
  command = "npm run build"
  publish = ".next"

# (İstəyə görə — assets üçün pass-through; qalsa da olar)
[[redirects]]
  from = "/images/*"
  to   = "/images/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to   = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/favicon*"
  to   = "/favicon.svg"
  status = 200

# YALNIZ lazım olanda baxım səhifəsini əl ilə açacaqsan.
# [[redirects]]
#   from = "/*"
#   to   = "/maintenance.html"
#   status = 200
#   force = true

# Maintenance səhifəsinə düz keçid üçün qalsın:
[[redirects]]
  from = "/maintenance"
  to   = "/maintenance.html"
  status = 200
