[build]
  command = "npm run build"
  publish = ".next"

# --- Assets always pass-through ---
[[redirects]]
  from = "/_next/*"
  to   = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/images/*"
  to   = "/images/:splat"
  status = 200

# --- ONLY PRODUCTION: show maintenance page ---
[context.production]
  [[context.production.redirects]]
    from = "/*"
    to   = "/maintenance.html"
    status = 200
    force = true
